### ISSUE TITLE
Commit Issue #1

### ISSUE THREAD

**Issue by rbcabreraUPM** [CS127-LAB-2NDSEM-2020-CABRERA/QUIAOIT#1]
```
if len(result) == 0:
			return "There is no recorded info on the given id number. It is possible that it is already deleted.", 200
```

change this to 404

		if len(result) == 0:
			return "Nothing to delete. Since, it is empty.", 304
change this to 404

		if len(result) == 0:
			return "Cannot update", 304
change this to 404

404 is the status code for _NOT_FOUND_

Well done for implementing error checking :D

**Comment by rdquiaoit** [comment]
Noted sir. Thank you.
